package com.voll.api.domain.models.enumeration;

/**
 * THIS ENUMERATION CLASS REPRESENTING MEDICAL SPECIALITIES IN THE CONTEXT OF THE APPLICATION'S DOMAIN.
 * This lists common medical specialities for doctors or healthcare providers.
 *
 * @author Ignacio Álvarez
 * @version 1.0
 * @since 2023-11-07
 */

public enum Speciality {

    // REPRESENTS THE MEDICAL SPECIALITY FOCUSED ON ORTHOPEDIC CONDITIONS AND TREATMENTS.
    ORTHOPEDICS,

    // REPRESENTS THE MEDICAL SPECIALITY FOCUSED ON HEART-RELATED CONDITIONS AND CARDIOLOGY TREATMENTS.
    CARDIOLOGY,

    // REPRESENTS THE MEDICAL SPECIALITY FOCUSED ON WOMEN'S REPRODUCTIVE HEALTH AND GYNECOLOGICAL TREATMENTS.
    GYNECOLOGY,

    // REPRESENTS THE MEDICAL SPECIALITY FOCUSED ON THE HEALTHCARE OF INFANTS, CHILDREN, AND ADOLESCENTS.
    PEDIATRICS
}
